### ISSUE TITLE
Getting 401 Unauthorized error

### ISSUE THREAD

**Issue by sairaut** [RodrigoRVieira/AzureADSampleAuthApp#1]
Hi,

When i am trying to use the token generated from MSAL and using on the postman for API, I am getting the error as 401 Unauthorized. 

Could you please share the Azure AD settings?

**Comment by RodrigoRVieira** [comment]
Hello @sairaut 

Please try following the procedures described in this link: https://docs.microsoft.com/en-us/skype-sdk/websdk/docs/troubleshooting/auth/aadauth-enableimplicitoauth

I forgot to add that to the README.

Let me know how it works for you ;)

**Comment by sairaut** [comment]
Hi,

I checked on Azure, this setting is already present. Any other thoughts?

**Comment by sairaut** [comment]
Btw, i am trying to use two different client Ids here. (One is for Web App
and other is for Web API) When i use same client ID then it works but when
i am putting 2 different client IDs then it is showing me 401 Unauthorized
error.

**Comment by RodrigoRVieira** [comment]
@sairaut 

Afaik you can't use the same backend to authorize more than one client Id (Azure Application).

If you have any other issue feel free to open a new ticket.

Regards
